### ISSUE TITLE
Using fakeroot + fakechroot + chroot.

### ISSUE THREAD

**Issue by luis-lavaire** [Nitrux/pnx#1]
Using these commands would reduce the required privileges for any operation; thus, making it more secure. As we're not operating on the real root filesystem (i.e. `/`), we don't need privileges.

However, we're using a location that is not writeable by unprivileged users: `/home`. We should consider using a more adequate location (perhaps inside the user's home directory, like `~/.pnx`).

**Comment by UriHerrera** [comment]
> We should consider using a more adequate location (perhaps inside the user's home directory, like ~/.pnx).

That would mean that each user would have an individual PNX folder; this will result in a substantial increment of disk space used.

**Comment by luis-lavaire** [comment]
Space is cheap, and this would also mean adding greater isolation between the system and `pnx` (see issue #2).

**Comment by UriHerrera** [comment]
Alright, if it increases isolation, it's okay.

**Comment by UriHerrera** [comment]
Close in favor of #3
