### ISSUE TITLE
Just broke my Arch installation.

### ISSUE THREAD

**Issue by luis-lavaire** [Nitrux/pnx#2]
`pnx` is using the **REAL** directories that `pacman` uses for storing metadata. If you issue the command `sudo pnx --remove-dirs`, it will break any system that uses `pacman` as it's main package manager.

**Comment by UriHerrera** [comment]
>  If you issue the command sudo pnx --remove-dirs, it will break any system that uses pacman as it's main package manager.

But you're not supposed to do that lol.

**Comment by luis-lavaire** [comment]
Yeah, one isn't supposed to use `pnx` in Arch-derived systems...

I think everything should be removed. Otherwise, we'll be cluttering the users' storage. Using `fakechroot` (issue #1) would help to improve this.
